# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56db5837dd9f971cfd3827984432c603ad578ac6f8a36c18d60d38e0b1ab52ce7c9c4dd6cadc57961f7f9918feb817184689f9cde2efaf758ebd75e972175ddd

test:
  secret_key_base: 705beeaebadac8c8189856e1e6f1b3f669ec22490183f1350dd66b36b5a6a6b4c22f5ddab9903585205efe30a03d69ae9ba6ea177354f869e7710e70fbc302d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
